# Premiers pas en Python
Formation pour apprendre python, la POO en python et quelques libraiires de Data Science

In [43]:
import numpy as np

In [4]:
print("Hello", "Antoine", "Matthias")
print("Hello", "Antoine", "Matthias", sep=", ")
print("Hello", "Antoine", end=" ")
print("Matthias")

Hello Antoine Matthias
Hello, Antoine, Matthias
Hello Antoine Matthias


In [22]:
data = [1, 4, 8, 15, 23 ]

In [23]:
data * 2

[1, 4, 8, 15, 23, 1, 4, 8, 15, 23]

In [24]:
'Pau' * 2

'PauPau'

In [25]:
data + [3, 5]

[1, 4, 8, 15, 23, 3, 5]

In [26]:
'Pau' + 'Toulouse'

'PauToulouse'

In [27]:
4 in data

True

In [28]:
4 not in data

False

In [33]:
data2 = [1, 4, 8, 15, 23]
data3 = data # partage de reference

In [32]:
print(data2 == data)
print(data3 == data)
print(data2 is data)
print(data3 is data)

True
True
False
True


In [35]:
data.append(55)
print(data)
print(data3)

[1, 4, 8, 15, 23, 55]
[1, 4, 8, 15, 23, 55]


In [36]:
data = [0, 1]
print(data)
print(data3)


[0, 1]
[1, 4, 8, 15, 23, 55]


In [39]:
14 % 4 # modulo

2

In [40]:
14 / 4

3.5

In [41]:
14 // 4

3

In [42]:
2**30

1073741824

## Exemple Numpy

In [46]:
v = np.array(data2)
v

array([ 1,  4,  8, 15, 23])

In [47]:
v * 2

array([ 2,  8, 16, 30, 46])

In [48]:
v * v

array([  1,  16,  64, 225, 529])

In [51]:
m = v.reshape((5,1))
m

array([[ 1],
       [ 4],
       [ 8],
       [15],
       [23]])

In [53]:
v @ m

array([835])

In [59]:
m2 = m @ m.T
m2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 120, 184],
       [ 15,  60, 120, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [55]:
m.shape

(5, 1)

In [56]:
v.shape

(5,)

In [60]:
m2.shape

(5, 5)

In [61]:
m2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
# transposed matrix shares data with original matrix
tm2 = m2.T
tm2.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [64]:
tm2[2,3]

120

In [65]:
m2.T = np.array([3])

AttributeError: attribute 'T' of 'numpy.ndarray' objects is not writable

In [66]:
m2.T[2,3] = 888

In [67]:
m2.T

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 888, 184],
       [ 15,  60, 120, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [69]:
tm2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 888, 184],
       [ 15,  60, 120, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [68]:
m2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 120, 184],
       [ 15,  60, 888, 225, 345],
       [ 23,  92, 184, 345, 529]])