# Premiers pas en Python
Formation pour apprendre python, la POO en python et quelques libraiires de Data Science

In [94]:
import numpy as np
import math
import statistics as stat

In [4]:
print("Hello", "Antoine", "Matthias")
print("Hello", "Antoine", "Matthias", sep=", ")
print("Hello", "Antoine", end=" ")
print("Matthias")

Hello Antoine Matthias
Hello, Antoine, Matthias
Hello Antoine Matthias


In [22]:
data = [1, 4, 8, 15, 23 ]

In [23]:
data * 2

[1, 4, 8, 15, 23, 1, 4, 8, 15, 23]

In [24]:
'Pau' * 2

'PauPau'

In [25]:
data + [3, 5]

[1, 4, 8, 15, 23, 3, 5]

In [26]:
'Pau' + 'Toulouse'

'PauToulouse'

In [27]:
4 in data

True

In [28]:
4 not in data

False

In [33]:
data2 = [1, 4, 8, 15, 23]
data3 = data # partage de reference

In [32]:
print(data2 == data)
print(data3 == data)
print(data2 is data)
print(data3 is data)

True
True
False
True


In [35]:
data.append(55)
print(data)
print(data3)

[1, 4, 8, 15, 23, 55]
[1, 4, 8, 15, 23, 55]


In [36]:
data = [0, 1]
print(data)
print(data3)


[0, 1]
[1, 4, 8, 15, 23, 55]


In [39]:
14 % 4 # modulo

2

In [40]:
14 / 4

3.5

In [41]:
14 // 4

3

In [42]:
2**30

1073741824

## Exemple Numpy

In [46]:
v = np.array(data2)
v

array([ 1,  4,  8, 15, 23])

In [47]:
v * 2

array([ 2,  8, 16, 30, 46])

In [48]:
v * v

array([  1,  16,  64, 225, 529])

In [51]:
m = v.reshape((5,1))
m

array([[ 1],
       [ 4],
       [ 8],
       [15],
       [23]])

In [53]:
v @ m

array([835])

In [59]:
m2 = m @ m.T
m2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 120, 184],
       [ 15,  60, 120, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [55]:
m.shape

(5, 1)

In [56]:
v.shape

(5,)

In [60]:
m2.shape

(5, 5)

In [61]:
m2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
# transposed matrix shares data with original matrix
tm2 = m2.T
tm2.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [64]:
tm2[2,3]

120

In [65]:
m2.T = np.array([3])

AttributeError: attribute 'T' of 'numpy.ndarray' objects is not writable

In [66]:
m2.T[2,3] = 888

In [67]:
m2.T

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 888, 184],
       [ 15,  60, 120, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [69]:
tm2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 888, 184],
       [ 15,  60, 120, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [68]:
m2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 120, 184],
       [ 15,  60, 888, 225, 345],
       [ 23,  92, 184, 345, 529]])

## basic datas

In [72]:
print(type(12)) # int (no limit)
print(type(12.3)) # float

<class 'int'>
<class 'float'>


In [73]:
x = 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111114
x + 1

1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111115

In [77]:
# floats : IEEE754
x=1E308
print(x)
print(x*2) # inf

1e+308
inf


In [85]:
nv = float('nan')
print(nv)
nv + 3
nv

nan


nan

In [87]:
dataWithNan = [ 1, 4, nv, 7]
dataWithNan

[1, 4, nan, 7]

In [96]:
# some stats with list of values containing NaN
# builtin functions : len, sum, min, max
# module statistics : mean, ...
print(len(dataWithNan))
print(sum(dataWithNan))
print(min(dataWithNan))
print(max(dataWithNan))
print(stat.mean(dataWithNan))


4
nan
1
7
nan


In [97]:
vDataWithNan = np.array(dataWithNan)
vDataWithNan

array([ 1.,  4., nan,  7.])

In [98]:
vDataWithNan.dtype

dtype('float64')

In [100]:
print(len(vDataWithNan))
print(np.sum(vDataWithNan))
print(np.min(vDataWithNan))
print(np.max(vDataWithNan))
print(np.mean(vDataWithNan))

4
nan
nan
nan
nan


In [101]:
print(len(vDataWithNan))
print(np.nansum(vDataWithNan))
print(np.nanmin(vDataWithNan))
print(np.nanmax(vDataWithNan))
print(np.nanmean(vDataWithNan))

4
12.0
1.0
7.0
4.0


In [104]:
np.sum(m2)

3369

In [107]:
m2

array([[  1,   4,   8,  15,  23],
       [  4,  16,  32,  60,  92],
       [  8,  32,  64, 120, 184],
       [ 15,  60, 888, 225, 345],
       [ 23,  92, 184, 345, 529]])

In [105]:
# sum of each column
np.sum(m2, axis=0)

array([  51,  204, 1176,  765, 1173])

In [106]:
# sum of each row
np.sum(m2, axis=1)

array([  51,  204,  408, 1533, 1173])

In [110]:
# check
np.sum(m2[:, 2])

1176

In [113]:
dataMarks = np.random.normal(12, 5, 1000000)
dataMarks

array([16.17924162, 10.23172017, 17.74489734, ...,  5.94806093,
        6.55210851,  9.25704333])

In [115]:
np.percentile(dataMarks, 95)

20.238989557074298

In [116]:
np.percentile(dataMarks, 5)

3.769519108009828

In [117]:
np.quantile(dataMarks, .95)

20.238989557074298

In [119]:
[np.quantile(dataMarks, .25*i) for i in range(1,4)]

[8.627632007141916, 12.009982118539028, 15.381386578250668]

## some loops

In [121]:
# for  iterate upon the values
for d in data2:
    print(d)

1
4
8
15
23


In [122]:
for letter in 'Toulouse':
    print(letter)

T
o
u
l
o
u
s
e


In [123]:
for i in range(5):  # from 0 included to 5 excluded
    print(i)

0
1
2
3
4


In [124]:
for i in range(1, 5):  # from 1 included to 5 excluded
    print(i)

1
2
3
4


In [126]:
# range objetcs are lazy
range(10)

range(0, 10)

In [128]:
# convert range object into a list
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [131]:
for i in range(len(data2)):
    print(i, data2[i], sep=': ')

0: 1
1: 4
2: 8
3: 15
4: 23


In [132]:
for i, v in enumerate(data2):
    print(i, v, sep=': ')

0: 1
1: 4
2: 8
3: 15
4: 23


In [133]:
for i, v in enumerate(data2, 1):
    print(i, v, sep=': ')

1: 1
2: 4
3: 8
4: 15
5: 23


In [137]:
# oldschool code
newData = []
for d in data2:
    newData.append(d+1)
newData

[2, 5, 9, 16, 24]

In [140]:
# comprehension list: list with for expression
[ d + 1 for d in data2 ]

[2, 5, 9, 16, 24]

In [142]:
# SyntaxError: invalid syntax
# d + 1 for d in data2

In [143]:
sum(d + 1 for d in data2)

56

In [145]:
# SyntaxError: Generator expression must be parenthesized
# sum(d + 1 for d in data2, 1000)
sum((d + 1 for d in data2), 1000)

1056

In [148]:
sum(i+v for i,v in enumerate(data2))

61

In [167]:
g = (d + 1 for d in data2)
g

<generator object <genexpr> at 0x0000026E38006970>

In [168]:
# extraction d'une donnée : step by step
next(g)

2

In [169]:
list(g)

[5, 9, 16, 24]

In [170]:
for row in m2:
    print(row)

[ 1  4  8 15 23]
[ 4 16 32 60 92]
[  8  32  64 120 184]
[ 15  60 888 225 345]
[ 23  92 184 345 529]


## containers

In [174]:
villes = [ "Toulouse", "Pau", "Bayonne" ]  # list
ville = ("Toulouse", 370000, 31000) # tuple (not modifiable)
ville_d = {"nom": "Toulouse", "pop": 370000, "cp": 31000}  # dict

In [175]:
ville[0]

'Toulouse'

In [181]:
v, p, c = ville  # unpack
print(v,p,c)

Toulouse 370000 31000


In [182]:
ville_d["nom"]

'Toulouse'

In [183]:
ville_d["pop"] += 1000
ville_d

{'nom': 'Toulouse', 'pop': 371000, 'cp': 31000}

In [81]:
for k,v in ville_d.items():
    print(k, v, sep= ' -> ')

nom -> Toulouse
pop -> 371000
cp -> 31000


## Text Data

In [82]:
ville = "Toulouse"

In [83]:
ville[::-1]

'esuoluoT'

In [85]:
ville[:], ville[:2], ville[2:], ville[2:5]

('Toulouse', 'To', 'ulouse', 'ulo')

In [87]:
ville[-2:], ville[2:-2]

('se', 'ulou')

In [88]:
ville[5:2], ville[-2:2]

('', '')

In [89]:
ville[5:2:-1], ville[-2:2:-1], ville[::2], ville[1::2]

('uol', 'suol', 'Tuos', 'olue')

In [92]:
list(range(0,10,2)), list(range(0,10,-1))

([0, 2, 4, 6, 8], [])

In [94]:
", ".join(villes)

'Toulouse, Pau, Bayonne'

In [95]:
temperatures = [25, 34, 41, 18]

In [98]:
", ".join(str(t) for t in temperatures)

'25, 34, 41, 18'

In [99]:
ville = "Toulouse"
pop = 370000

In [100]:
ville + " (pop = " + str(pop) + ")"

'Toulouse (pop = 370000)'

In [102]:
# python 1-2 : deprecated
"%s (pop = %s)" % (ville,pop)

'Toulouse (pop = 370000)'

In [103]:
# python
"{} (pop = {})".format(ville, pop)

'Toulouse (pop = 370000)'

In [104]:
"{0} (pop = {1}) ; {0} ville rose".format(ville, pop)

'Toulouse (pop = 370000) ; Toulouse ville rose'

In [108]:
densite = 50.300122222222

In [110]:
# https://docs.python.org/3/library/string.html#formatstrings
"{0} (pop = {1} ; densité = {2:.2f})".format(ville, pop, densite)

'Toulouse (pop = 370000 ; densité = 50.30)'

In [111]:
# python 3.6
f"{ville} (pop = {pop} ; densité = {densite:.2f})"

'Toulouse (pop = 370000 ; densité = 50.30)'

In [112]:
"aujourd'hui"

"aujourd'hui"

In [113]:
"aujourd'hui, je dis \"il fait beau\""

'aujourd\'hui, je dis "il fait beau"'

In [117]:
texte = "perroquet 🦜 in 🇫🇷"
texte

'perroquet 🦜 in 🇫🇷'

In [118]:
texte.encode('UTF-8')

b'perroquet \xf0\x9f\xa6\x9c in \xf0\x9f\x87\xab\xf0\x9f\x87\xb7'

In [119]:
texte = "baguette à 1,20€"

In [121]:
# UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac'
# texte.encode('ISO8859-1')

In [122]:
texte.encode('ISO8859-15')

b'baguette \xe0 1,20\xa4'

In [123]:
texte.encode('cp1252')

b'baguette \xe0 1,20\x80'

In [126]:
labelUTF8 = texte.encode('UTF-8')
labelUTF8

b'baguette \xc3\xa0 1,20\xe2\x82\xac'

In [127]:
labelUTF8.decode()

'baguette à 1,20€'